name: Add issues and pull requests to a project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    if: |
      github.event_name == 'issues' || ! github.event.pull_request.head.repo.fork
    steps:
      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          permissions: >-
            {}
          repositories: >-
            []
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/users/suzuki-shunsuke/projects/5
          github-token: ${{ steps.token.outputs.token }}
