---
name: test container
on: pull_request
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/suzuki-shunsuke/test-github-action-2:0.0.2
    steps:
      - run: whoami
      - uses: actions/checkout@v4
      - run: ls -lh
