---
name: delete branch
on: pull_request
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: git push origin --delete "lock/foo"
