---
name: test cancel
on: pull_request
jobs:
  foo:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3600
  bar:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [foo]
    if: failure()
    steps:
      - run: exit 1
