---
name: test
on: pull_request
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          version: v0.10.4
      - name: Login to Quay
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx
        env:
          DOCKERIO_ORG: suzuki_shunsuke
          PLATFORM: linux/amd64
          TARGET: test-argo-workflows
        run: |
          set -eux
          tag=$(basename $GITHUB_REF)
          if [ $tag = "main" ]; then
            tag="latest"
          fi
          tag_suffix=$(echo $PLATFORM | sed -r "s/\//-/g")
          image_name="${DOCKERIO_ORG}/${TARGET}:${tag}-${tag_suffix}"

          docker buildx build \
            --output "type=image,push=true" \
            --platform="${PLATFORM}" \
            --provenance=false \
            --tag quay.io/$image_name .

  push-images:
    name: Push manifest with all images
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Login to Quay
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0
        with:
          cosign-release: 'v2.2.3'

      - name: Push Multiarch Image
        env:
          DOCKERIO_ORG: suzuki_shunsuke
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
        run: |
          set -euo pipefail
          : ${DOCKER_CONFIG:=~/.docker}

          echo $(jq -c '. + { "experimental": "enabled" }' ${DOCKER_CONFIG}/config.json) > ${DOCKER_CONFIG}/config.json

          docker_org=$DOCKERIO_ORG

          tag=$(basename $GITHUB_REF)
          if [ $tag = "main" ]; then
            tag="latest"
          fi

          targets="test-argo-workflows"
          tag_suffix=linux-amd64
          for target in $targets; do
            image_name="${docker_org}/${target}:${tag}"
            docker manifest create "quay.io/$image_name" "quay.io/${image_name}-${tag_suffix}"

            docker manifest push quay.io/${image_name}

            docker manifest inspect --verbose quay.io/${image_name}-${tag_suffix}

            digest=$(docker manifest inspect --verbose quay.io/${image_name}-${tag_suffix} |
              jq -r 'if type=="object"
                  then .Descriptor.digest
                  else .[] | select(.Descriptor.platform.architecture=="amd64" and
                  .Descriptor.platform.os=="linux") | .Descriptor.digest
                  end')
            echo "digest: $digest"
            cosign sign -y --key env://COSIGN_PRIVATE_KEY "quay.io/${docker_org}/${target}@${digest}"
          done
