---
name: delete branch
on: pull_request
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: echo "$TOKEN" | gh auth login --with-token
        env:
          TOKEN: ${{secrets.GH_TOKEN}}
      - run: git push origin --delete "lock/foo"
