---
name: test octo sts
on:
  workflow_dispatch:
    inputs:
      identity:
        description: 'The identity'
        required: true
        default: 'foo'
      scope:
        description: 'scope'
        required: true
        default: 'suzuki-shunsuke/test-github-action-2'
      issue_repo:
        description: 'issue repo'
        required: true
        default: 'suzuki-shunsuke/test-github-action-2'
      issue_number:
        description: 'issue number'
        required: true
        default: '4'
jobs:
  foo:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens.
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{inputs.scope}}
          identity: ${{inputs.identity}}
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh repo list
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          REPO: ${{ inputs.issue_repo }}
          NUMBER: "5"
        run: |
          gh -R "$REPO" pr comment "$NUMBER" --body "Test Octo STS"
