---
name: test octo sts
on: workflow_dispatch
jobs:
  foo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens.
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: suzuki-shunsuke/test-github-action-2
          identity: foo
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh -R "$GITHUB_REPOSITORY" repo list
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh -R "$GITHUB_REPOSITORY" issue comment 4 --body "Test Octo STS"
